// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// centering
arma::mat centering(const arma::mat& A);
RcppExport SEXP _KernelIR_centering(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(centering(A));
    return rcpp_result_gen;
END_RCPP
}
// handle_duplicates_and_ties
IntegerMatrix handle_duplicates_and_ties(NumericMatrix X, IntegerMatrix nn_idx, NumericMatrix nn_dists, int Knn);
RcppExport SEXP _KernelIR_handle_duplicates_and_ties(SEXP XSEXP, SEXP nn_idxSEXP, SEXP nn_distsSEXP, SEXP KnnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nn_idx(nn_idxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nn_dists(nn_distsSEXP);
    Rcpp::traits::input_parameter< int >::type Knn(KnnSEXP);
    rcpp_result_gen = Rcpp::wrap(handle_duplicates_and_ties(X, nn_idx, nn_dists, Knn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_KernelIR_centering", (DL_FUNC) &_KernelIR_centering, 1},
    {"_KernelIR_handle_duplicates_and_ties", (DL_FUNC) &_KernelIR_handle_duplicates_and_ties, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_KernelIR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
