# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

centering <- function(A) {
    .Call(`_KernelIR_centering`, A)
}

handle_duplicates_and_ties <- function(X, nn_idx, nn_dists, Knn) {
    .Call(`_KernelIR_handle_duplicates_and_ties`, X, nn_idx, nn_dists, Knn)
}

knn_tie_duplicate_aware_cpp <- function(X, nn_idx, nn_dists, Knn, tol = 1e-12) {
    .Call(`_KernelIR_knn_tie_duplicate_aware_cpp`, X, nn_idx, nn_dists, Knn, tol)
}

